name: Metrics

on:
  push:
    branches: [ main ]           # real runs on merges into main
  schedule:
    - cron: "0 0 * * *"          # daily updates at midnight CET
  workflow_dispatch: {}          # manual trigger for testing

permissions:
  contents: read                # only need to checkout
  pages: write                  # to deploy to GitHub Pages
  id-token: write               # for provenance checks

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get GitHub App token
        id: app_token
        uses: peter-murray/workflow-application-token-action@v4
        with:
          application_id: ${{ secrets.METRICS_APP_ID }}
          application_private_key: ${{ secrets.METRICS_APP_PRIVATE_KEY }}

      - name: Generate metrics SVG
        uses: lowlighter/metrics@v3.34
        with:
          config_timezone: Europe/Paris
          plugin_achievements: 'yes'
          plugin_achievements_limit: 0
          plugin_achievements_secrets: 'yes'
          plugin_activity: 'yes'
          plugin_followup: 'yes'
          plugin_followup_sections: repositories, user
          plugin_languages: 'yes'
          plugin_languages_details: bytes-size, percentage
          plugin_notable: 'yes'
          plugin_notable_filter: stars:>1000
          plugin_notable_repositories: 'yes'
          plugin_stargazers: 'yes'
          token: ${{ steps.app_token.outputs.token }}

      - name: Dry-run push (optional)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: git push --dry-run origin main   # just to verify push rights# deploy artifact to GitHub Pages :contentReference[oaicite:1]{index=1}
